version: "3.6"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - 5432:5432
  api:
    image: sample/api
    environment: 
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - ConnectionStrings__Default=host=postgres;user id=postgres;password=Password12!;database=Outbox;
    build:
      context: ./src
      dockerfile: Dockerfile.api
    ports:
     - "5000:80"
  service:
    image: sample/worker
    environment: 
     - ConnectionStrings__Default=host=postgres;user id=postgres;password=Password12!;database=Outbox;
    build:
      context: ./src
      dockerfile: Dockerfile.worker
