FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ../. .
RUN ls -al
RUN dotnet restore "Sample.Worker/Sample.Worker.csproj"


RUN dotnet publish -c Release -o /app Sample.Worker/Sample.Worker.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Sample.Worker.dll"]
